language: ruby
rvm:
  - 2.1.1
env:
  - DB=postgresql
before_script:
  - psql -c 'create database momentum_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:reset --trace
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake
deploy:
  # on:
  #   tags: true
  provider: heroku
  strategy: git
  api_key: "1bd0640d-aca3-4679-997f-76b9a82cfaf8"
  app: "momentum-app"
  run:
    - "rake db:migrate"
    - restart
