language: ruby
rvm:
  - 2.1.1
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - bundle exec bundle install --binstubs --local --path vendor
  - psql -c 'create database momentum_test' -U postgres
deploy:
  provider: heroku
  strategy: git
  api_key: "1bd0640d-aca3-4679-997f-76b9a82cfaf8"
  app: "momentum-app"
  on:
    tags: true
  run:
      - "rake db:migrate"
      - restart
